---
portworx_namespace: "portworx"
stork_pod_label: "name=stork"
stork_binary_path: "/storkctl/linux/storkctl"
dr_namespace: "boutique"
migration_name: "boutique-migration"
# Must specify at least one of the cluster pair options. Admin cluster pairs take precedence when provided
admin_cluster_pair: ""
cluster_pair: ""
