---
- name: Run Portworx DR Bubble Test
  hosts: localhost
  connection: local

  vars:
    secondary_kubeconfig: ""

  tasks:
    - name: Run bubble test clone
      ansible.builtin.include_role:
        name: bubble-test
      vars:
        kubeconfig: "{{ secondary_kubeconfig }}"
