---
- name: Create Migration
  hosts: localhost
  connection: local

  vars:
    primary_kubeconfig: ""
    admin_cluster_pair: "admin-cluster-pair"
    portworx_namespace: "portworx"
    dr_namespace: "boutique"
    migration_name: "boutique-migration"

  tasks:
    - name: Create migration
      ansible.builtin.include_role:
        name: create-migration
      vars:
        kubeconfig: "{{ primary_kubeconfig }}"
